FROM tidair/pysmurf-server-base:%%PYSMURF_SERVER_BASE_VERSION%%

# Prepare directory to hold FW and config file
RUN mkdir -p /tmp/fw/ && chmod -R a+rw /tmp/fw/

# Copy all firmware related files, which are in the local_files directory
COPY local_files /tmp/fw

# Set the working directory to the root
WORKDIR /

# Expose the server arguments into a environmental variable
ENV START_SERVER_ARGS "%%SERVER_ARGS%%"

# Define the entrypoint
ENTRYPOINT ["start_server.sh",%%SERVER_ARGS%%]
